apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: davidhei/davidhei-k8s-polybot-dev:0.0.5
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: TELEGRAM_TOKEN
#        readinessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#          initialDelaySeconds: 15
#          periodSeconds: 20
