apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5-hpa
  namespace: dev  # Change to 'prod' for production environment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
